- name: Create kubeadm config file
  template:
    dest: /etc/kubeadm.yml
    src: "{{ kubeadm_template }}"
    mode: 0600

- name: Kubeadm pull images
  shell: 'kubeadm config images pull --config /etc/kubeadm.yml'

- name: delete kubeadm config
  file:
    path: /etc/kubeadm.yml
    state: absent
